set number
set smartindent
syntax on
set background=dark
colorscheme gruvbox

" open nerdtree automatically and ove cursor to window
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif
" close vim if nerdtree is last open
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
