#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ffffffcc'  # default
T='#eeeeeeee'  # text
W='#880000bb'  # wrong
V='#bbbbbbbb'  # verifying
Y='#99ff20bb'  # highlights

i3lock \
    --insidevercolor=$C   \
    --ringvercolor=$V     \
    --greetertext="f * c k  o f f" \
    --greetercolor=$T \
    --greeterpos="x+955:y+420" \
    --greeter-font='monospace' \
    \
    --insidewrongcolor=$C \
    --ringwrongcolor=$W   \
    \
    --insidecolor=$B      \
    --ringcolor=$D        \
    --linecolor=$B        \
    --separatorcolor=$D   \
    \
    --verifcolor=$T        \
    --veriftext="" \
    --wrongcolor=$T        \
    --wrongtext="" \
    --noinputtext="" \
    --timecolor=$T        \
    --datecolor=$T        \
    --layoutcolor=$T      \
    --keyhlcolor=$Y       \
    --bshlcolor=$Y        \
    \
    --screen 1            \
    --blur 5              \
    --clock               \
    --indicator           \
    --timestr="%H:%M:%S"  \
    --time-font="monospace" \
    --datestr="%A, %m %Y" \
    --date-font='monospace' \
