# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=1000
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/hexated/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# prompt config
PROMPT='%F{magenta}%1n%f@%F{yellow}%1m%f: %F{cyan}%~%f %# '

zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'
alias ls='ls --color=auto'
alias grep='grep --color=auto'

PATH=~/bin:$PATH
export PATH
